[package]
name = "libmavsdk"
version = "0.1.0"
authors = ["Ildar Sadykov <irsdkv@gmail.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.3", features = ["compat", "alloc"] }
tonic = "0.1.0-alpha.5"
bytes = "0.4"
prost = "0.5"

tokio = "=0.2.0-alpha.6"
#futures-preview = { version = "=0.3.0-alpha.19", default-features = true, features = ["alloc"]}
async-stream = "0.1.2"
http = "0.1"
tower = "=0.3.0-alpha.2"

# Required for wellknown types
prost-types = "0.5"

async-trait = "0.1.21"
async-std = "1.3.0"

[build-dependencies]
tonic-build = "0.1.0-alpha.5"