[package]
name = "libmavsdk"
version = "0.1.0"
authors = ["Ildar Sadykov <irsdkv@gmail.com>"]
edition = "2018"

[dependencies]
tonic = "0.1.0-beta.1"
bytes = "0.4"
prost = "0.5"

futures = { version = "0.3", default-features = false, features = ["alloc"]}

[dev-dependencies]
async-std = "1.3.0"
futures = { version = "0.3", default-features = true}
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }

[build-dependencies]
tonic-build = "0.1.0-beta.1"
